apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: bluegreen
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-09-03T05:24:00Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: blue-green-service
  namespace: default
  resourceVersion: "41336"
  uid: d3037956-4064-4135-9dc5-940d79bb3d6f
spec:
  clusterIP: 10.96.156.23
  clusterIPs:
  - 10.96.156.23
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue-green-demo
    version: blue
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
